function interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)

fig = figure('Name','Etajele amplificării cu TMOS',...
'Units','normalized',...
'Position',[0 0 0.95 0.9],...
'NumberTitle','off','color',[0 0.2 0]);

title=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.3 0.87 0.4 0.06],...
'backgroundcolor','[0 0.2 0]',...
'FontName','Cambria',...
'Fontsize',25,...
'Fontweight','bold',...
'foregroundcolor','white',...
'String','ETAJELE AMPLIFICĂRII CU TMOS');

%
bt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.01 0.8 0.1 0.03],...
'backgroundcolor','[0 0.2 0]',...
'FontName','Arial',...
'Fontsize',14,...
'foregroundcolor','white',...
'String','Configurații:');
bpu=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Backgroundcolor',[0.4660 0.4740 0.1880],...
'ForegroundColor','w',...
'Position',[0.01 0.75 0.1 0.05],...
'Fontsize',14,...
'Value',z,...
'String','Sursă comună|Grilă comună|Drenă comună',...
'Callback','z=get(gco,''Value''),close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

im1=imshow(('sursacomuna.JPG'),'parent',axes('Position',[0.01 0.32 0.3 0.4]));
im2=imshow(('grilacomuna1.JPG'),'parent',axes('Position',[0.01 0.32 0.3 0.4]));
im3=imshow(('drenacomuna.JPG'),'parent',axes('Position',[0.01 0.32 0.3 0.4]));

if z==1
 set(im2,'Visible','off');
 set(im3,'Visible','off');
elseif z==2
 set(im1,'Visible','off');
 set(im3,'Visible','off');
elseif z==3
 set(im1,'Visible','off');
 set(im2,'Visible','off');
end
%

Parametrii = uibuttongroup('Visible','on',...
    'Backgroundcolor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'FontSize',15,...
    'Title','Parametrii de intrare',...
    'TitlePosition','centertop',...
    'Position',[0.01 0.1 0.35 0.2 ]);

%btne txt pt. param.(vdd,beta,rg1,rg2,rd)

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.055 0.87 0.12 0.1],...
    'BackgroundColor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String','VDD [V]',...
    'Parent',Parametrii);

VDDUP = uicontrol ('Style','pushbutton',...
'Units','normalized',...
'Position',[0.055 0.5 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','white',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','VDD=VDD+1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

VDDUP1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.055 0.5 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','white',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii);

if VDD==20
    set(VDDUP1,'Visible','on');
    set(VDDUP,'Visible','off');
end

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.055 0.35 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','white',...
'String',VDD,...
'Fontsize',12,...
'Parent', Parametrii);

VDDDOWN=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.055 0.2 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','white',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','VDD=VDD-1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

VDDDOWN1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.055 0.2 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','white',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii);

if VDD==12
    set(VDDDOWN1,'Visible','on');
    set(VDDDOWN,'Visible','off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.25 0.87 0.12 0.1],...
    'BackgroundColor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String','BETA []',...
    'Parent',Parametrii);

BETAUP=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.26 0.5 0.1 0.15],...
    'backgroundcolor',[0 0.2 0],...
    'foregroundcolor','w',...
    'String',char(708),...
    'Fontsize',12,...
    'Parent', Parametrii,...
    'Callback','BETA=BETA+0.25,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');
BETAUP1=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.26 0.5 0.1 0.15],...
    'Visible','off',...
    'backgroundcolor',[0 0.2 0],...
    'foregroundcolor','w',...
    'String',char(708),...
    'Fontsize',12,...
    'Parent', Parametrii);

if BETA == 1.5
    set(BETAUP1,'Visible','on');
    set(BETAUP,'Visible','off');
end

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.26 0.35 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',BETA,...
'Fontsize',12,...
'Parent', Parametrii);

BETADOWN=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.26 0.2 0.1 0.15],...
    'backgroundcolor',[0 0.2 0],...
    'foregroundcolor','w',...
    'String',char(709),...
    'Fontsize',12,...
    'Parent', Parametrii,...
    'Callback','BETA=BETA-0.25,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');
BETADOWN1=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.26 0.2 0.1 0.15],...
    'Visible','off',...
    'backgroundcolor',[0 0.2 0],...
    'foregroundcolor','w',...
    'String',char(709),...
    'Fontsize',12,...
    'Parent', Parametrii);

if BETA==0.25
    set(BETADOWN1,'Visible','on');
    set(BETADOWN,'Visible','off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.45 0.87 0.12 0.1],...
    'BackgroundColor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'String','RG1 [MΩ]',...
    'FontSize',12,...
    'Parent',Parametrii);

RG1UP=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.45 0.5 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RG1=RG1+1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

RG1UP1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.45 0.5 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii);



if RG1 == 4
    set(RG1UP1,'Visible', 'on');
    set(RG1UP,'Visible', 'off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.45 0.35 0.1 0.15],...
    'BackgroundColor',[0 0.2 0],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String',RG1,...
    'Parent',Parametrii);

RG1DOWN=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.45 0.2 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RG1=RG1-1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

RG1DOWN1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.45 0.2 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii);

if RG1==1
    set(RG1DOWN1,'Visible','on');
    set(RG1DOWN,'Visible','off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.87 0.12 0.1],...
    'BackgroundColor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String','RG2 [MΩ]',...
    'Parent',Parametrii);
RG2UP=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.65 0.5 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RG2=RG2+1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');
RG2UP1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.65 0.5 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii);

if RG2 == 6
    set(RG2UP1,'Visible', 'on');
    set(RG2UP,'Visible', 'off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.35 0.1 0.15],...
    'BackgroundColor',[0 0.2 0],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String',RG2,...
    'Parent',Parametrii);
RG2DOWN=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.65 0.2 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RG2=RG2-1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

RG2DOWN1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.65 0.2 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii);

if RG2==3
    set(RG2DOWN1,'Visible','on');
    set(RG2DOWN,'Visible','off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.85 0.87 0.12 0.1],...
    'BackgroundColor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String','RD [KΩ]',...
    'Parent',Parametrii);
RDUP=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.5 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RD=RD+1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');
RDUP1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.5 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(708),...
'Fontsize',12,...
'Parent', Parametrii);

if RD == 20
    set(RDUP1,'Visible', 'on');
    set(RDUP,'Visible', 'off');
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.85 0.35 0.1 0.15],...
    'BackgroundColor',[0 0.2 0],...
    'ForegroundColor','w',...
    'FontSize',12,...
    'String',RD,...
    'Parent',Parametrii);
RDDOWN=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.2 0.1 0.15],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii,...
'Callback','RD=RD-1,close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

RDDOWN1=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.2 0.1 0.15],...
'Visible','off',...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String',char(709),...
'Fontsize',12,...
'Parent', Parametrii);

if RD==5
    set(RDDOWN1,'Visible','on');
    set(RDDOWN,'Visible','off');
end

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.12 0.75 0.19 0.05],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String','Schema echivalenta curent continuu',...
'Fontsize',12,...
'Callback','schechivCC(z)');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.12 0.70 0.19 0.05],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String','Schema echivalenta la semnal mic',...
'Fontsize',12,...
'Callback','schemasemnalmic(z)');


if z==1

ID = 1.2;
vgs = Vp + sqrt(ID/BETA);
vds = VDD - (RD*ID) -(RS*ID);

rds=Va/ID;
gm = 2*sqrt(BETA*ID);
Rin = (RG1*RG2)/(RG1+RG2);
Rout = (rds*RD)/(rds+RD);
Av = -gm*Rout;
end

if z == 2

ID = 1.2;
vgs = Vp + sqrt(ID/BETA);
vds = VDD - (RD*ID) + vgs;

rds=Va/ID;
gm = 2*sqrt(BETA*ID);
Rin = (1/gm)*10^(-6);
Rout = (rds*RD)/(rds+RD);
Av = gm*Rout;


end

if z == 3
ID = 1.2;
vgs = Vp + sqrt(ID/BETA);
vds = VDD-ID*RS;

gm = 2*sqrt(BETA*ID);
Rin = (RG1*RG2)/(RG1+RG2);
Rout = ((RS*(1/gm))/(RS+(1/gm)));
Av= (gm*RS)/(1+(gm*RS));

end
PunctStTF=uibuttongroup('Visible','on',...
    'backgroundcolor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'Title','Pct.-ul static de functionare',...
    'FontSize',12,...
    'TitlePosition','centertop',...
    'Position',[0.33 0.6 0.2 0.2]);

p1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.15 0.7 0.3 0.15],...
'String','ID [mA] =',...
'Fontsize',12,...
'Parent',PunctStTF)
p2=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.6 0.7 0.2 0.15],...
'String',ID,...
'Fontsize',12,...
'Parent',PunctStTF);
p3=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.15 0.45 0.3 0.15],...
'String','vgs [V] =',...
'Fontsize',12,...
'Parent',PunctStTF);
p4=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.6 0.45 0.2 0.15],...
'String',vgs,...
'Fontsize',12,...
'Parent',PunctStTF);
p5=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.15 0.2 0.3 0.15],...
'String','vds [V] =',...
'Fontsize',12,...
'Parent',PunctStTF);
p6=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','white',...
'Position',[0.6 0.2 0.2 0.15],...
'String',vds,...
'Fontsize',12,...
'Parent',PunctStTF);

PSM=uibuttongroup('Visible','on',...
    'backgroundcolor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'Title','Parametrii de semnal mic',...
    'FontSize',12,...
    'TitlePosition','centertop',...
    'Position',[0.55 0.6 0.2 0.2]);
b1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.15 0.8 0.3 0.15],...
'String','gm [mS] =',...
'Fontsize',12,...
'Parent',PSM);

b2=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.6 0.8 0.2 0.15],...
'String',gm,...
'Fontsize',12,...
'Parent',PSM);

b3=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.15 0.6 0.3 0.15],...
'String','Av =',...
'Fontsize',12,...
'Parent',PSM);

b4=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.6 0.6 0.2 0.15],...
'String',Av,...
'Fontsize',12,...
'Parent',PSM);

b5=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.15 0.4 0.3 0.15],...
'String','Rin [MΩ] =',...
'Fontsize',12,...
'Parent',PSM);

b6=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.6 0.4 0.2 0.15],...
'String',Rin,...
'Fontsize',12,...
'Parent',PSM);

b7=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.15 0.2 0.3 0.15],...
'String','Rout [KΩ] =',...
'Fontsize',12,...
'Parent',PSM);

b8=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.6 0.2 0.2 0.15],...
'String',Rout,...
'Fontsize',12,...
'Parent',PSM);

hello=uibuttongroup('Visible','on',...
     'backgroundcolor',[0.4660 0.4740 0.1880],...
    'ForegroundColor','w',...
    'Title','Parametrii semnalelor',...
    'FontSize',12,...
    'TitlePosition','centertop',...
    'Position',[0.78 0.6 0.2 0.2]);
h1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.05 0.75 0.4 0.15],...
'String','Amplitudine [V]:',...
'Fontsize',12,...
'Parent',hello);

h2=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.05 0.45 0.4 0.15],...
'String','Offset [V]:',...
'Fontsize',12,...
'Parent',hello);

h3=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.05 0.15 0.4 0.15],...
'String','Frecventa [Hz]:',...
'Fontsize',12,...
'Parent',hello);

h4=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.5 0.75 0.4 0.15],...
'Fontsize',12,...
'String',A,...
'Parent',hello,...
'Callback','A=str2num(get(gco,''String'')),close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

h5=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.5 0.45 0.4 0.15],...
'Fontsize',12,...
'String',V,...
'Parent',hello,...
'Callback','V=str2num(get(gco,''String'')),close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

h6=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor',[0 0.2 0],...
'ForegroundColor','w',...
'Position',[0.5 0.15 0.4 0.15],...
'Fontsize',12,...
'String',f,...
'Parent',hello,...
'Callback','f=str2num(get(gco,''String'')),close,interfata_tmos(z,RS,VDD,BETA,RG1,RG2,RD,Vp,Va,f,V,A)');

T=1/f; 
t=0:0.0001:2*T; 
t1=0:0.0001:2*T; 
y1=V+A.*sin(2*pi*f*t); 
y2=Av.*A.*sin(2*pi*f*t);
subplot('position',[0.45 0.1 0.52 0.4]);

plotyy(t,y1,t1,y2);
grid on;
%title('Semnalul de iesire in functie de semnalul de intrare','Fontsize',12);
legend('V in','V out');
xlabel('timp [s]', 'Color','white');
ylabel('Amplitudine [V]', 'Color','white');


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.4 0.83 0.06 0.03],...
'backgroundcolor',[0 0.2 0],...
'foregroundcolor','w',...
'String','Documentatie',...
'Fontsize',12,...
'Callback','open(''Componența proiectului.pdf'')');





