function schechivCC(z)

fig = figure ('Name','Circuitul echivalent in curent comtinuu',...
'Units','normalized',...
'Position',[0 0 0.9 0.9],...
'NumberTitle','off','color',[0 0.2 0]);

im4=imshow(('schechivCCSC.JPG'),'parent',axes('Position',[0.25 0.25 0.76 0.5]));
im5=imshow(('schechivCCGC.JPG'),'parent',axes('Position',[0.25 0.25 0.76 0.5]));
im6=imshow(('schechivCCDC.JPG'),'parent',axes('Position',[0.25 0.25 0.76 0.5]));

Bpu=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.1 0.74 0.2 0.05],...
'Backgroundcolor',[0.4660 0.4740 0.1880],...
'foregroundcolor','white',...
'Fontsize',12,...
'Value',z,...
'String','Sursa comuna|Grila comuna|Drena comuna',...
'Callback','z=get(gco,''Value''),close,schechivCC(z)');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.1 0.64 0.1 0.05],...
'Backgroundcolor',[0.4660 0.4740 0.1880],...
'foregroundcolor','white',...
'String','Inapoi',...
'Fontsize',12,...
'Callback','close');

if z==1
 set(im5,'Visible','off');
 set(im6,'Visible','off');
elseif z==2
 set(im4,'Visible','off');
 set(im6,'Visible','off');
elseif z==3
 set(im4,'Visible','off');
 set(im5,'Visible','off');
end